### ISSUE TITLE
About case with bodys touching the boundary

### ISSUE THREAD

**Issue by frankyugit** [barbagroup/PetIBM#133]
Dear guys,

Looks like a lot of updates since last year, excellent work~~
Wish to discuss a question on whether the algorithm of Taira & Colonius will work for the case with _**bodies touching or embedded into the boundary**_, as these are quite common situations like back or forward irregular steps
Wish some tips and open discussion

Best

**Comment by piyueh** [comment]
Thank you, @frankyugit!

Here are my understanding of your questions and my thoughts.

1. By "bodies touching" you mean collisions of moving bodies and walls? Currently, we don't have any mechanism to handle this situation in PetIBM. And I think this issue is not related to the method of Taira & Colonius. What proposed by Taira & Colonius is just a numerical method to solve Navier-Stokes equations with immersed body-force terms. And how to handle collisions of bodies, in my imagination, is probably a matter of the design of overall solving algorithm/procedure. For example, in my thought, after obtaining the motions/movements of bodies through Taira & Colonius' method, we can add an extra step in the solver to examine how close two bodies are and then handle them. Therefore, handling collisions is not related to the method of Taira & Colonius.

2. Does "embedded into the boundary" mean using immersed-boundary methods to handle the bounding walls of internal flow? If yes, then PetIBM and the method of Taira & Colonius should be able to handle that. From my understanding, all immersed-boundary methods should be capable of this, because there seems no difference between a bounding wall of internal flow and the surface of a body. I believe it's just the matter of how good or how efficient it is to do this. Our research is purely external flow, so we don't have experience with this use case in PetIBM. Nevertheless, I think it may not be efficient to treat bounding walls as immersed boundaries. And that may be why many people trying to combine unstructured grids and immersed-boundary methods. That is, use unstructured grids to handle bounding walls of internal flow, and use immersed-boundary methods to handle the moving bodies in that flow. 

We are happy to discuss further. If you can let us know what kind of simulations or cases you're interested in, it will be great because we can have a better understanding of your questions.
