### ISSUE TITLE
Multiple Moving bodies

### ISSUE THREAD

**Issue by OmidAt** [barbagroup/PetIBM#141]
Dear All,

I would like to know weather PetIBM is capable of handling Multiple Moving bodies simultaneously?

Thanks,
Omid

**Comment by piyueh** [comment]
**Short answer**:
Multiple static bodies: yes
Multiple moving bodies: not without extra coding

**Long answer**:
There are two parts in PetIBM: 1) an API library and 2) application solvers written with the help of the library. The main goal of PetIBM is to provide the API library so that users can create different kinds of flow solvers easily. And the application solvers are the solvers we have created for our research. In current existing application solvers, all IBM solvers can handle multiple static bodies. But for moving bodies, the current design is that users have to write some code to specify the movements of the bodies. Here is [an example](https://github.com/barbagroup/PetIBM/tree/master/examples/api_examples/oscillatingcylinder2dRe100_GPU) of the IBM solver with one moving body in the flow. This is also an example of how to use the API library to create users' own solvers.

So, regarding multiple moving bodies, if you are willing to write some code, then yes, PetIBM can help you create such an IBM solver. But if what you are looking for is a ready-to-use solver, then no, our current existing application solvers don't support this feature.

**Comment by OmidAt** [comment]
Thanks a lot!
