### ISSUE TITLE
Divergence of Poisson solver after running more than 15000 time steps

### ISSUE THREAD

**Issue by shi-guangyu** [barbagroup/PetIBM#154]
Hi, guys,

I got a divergence problem when I was running the example in $PETIBM_INSTALL/examples/decoupledibpm/cylinder2dRe100_GPU. The error occurred after running more than 15000 time steps. I'm attaching the all the file for the case
[cylinder2dRe100_CPU.zip](https://github.com/barbagroup/PetIBM/files/4314942/cylinder2dRe100_CPU.zip)

 for your reference.

BTW, I'm using CPU only, so I changed the config.yaml and replaced the original poisson_solver.info using the one under $PETIBM_INSTALL/examples/ibpm/cylinder2dRe550.

Any idea how should modify the parameter to make it more robust?

Many thanks in advance.

Kind regards;

Guangyu

**Comment by piyueh** [comment]
Hi @shi-guangyu 

Could you please try the biconjugate gradient stabilized Krylov solver? i.e., in your **_poisson_solver.info_**, replace the following line
```
-poisson_ksp_type cg
```
with
```
-poisson_ksp_type bcgs
```

The ibpm solver and decoupled-ibpm solver have different Poisson matrices, so the Krylov solvers and preconditioners may need different configurations. The **_poisson_solver.info_** you copied uses a GAMG preconditioner, which occasionally gives us problems and requires fine-tuning. But usually using the biconjugate gradient stabilized Krylov solver can reduce the impact of solver/preconditioner parameters.

**Comment by shi-guangyu** [comment]
Thanks a lot, Pi-Yueh. I'll give a try and let you know the result.

Is this also appliable to the rigid_kinematics_solver, which is based on decoupled IBPM as well?

**Comment by piyueh** [comment]
Yes. The Poisson matrix in rigid_kinematics_solver is the same as the one in decoupled ibpm. And actually, it's a standard finite-difference Poisson matrix.

If you will be seriously using CPU solvers in the future, I'll suggest you enable HYPRE when installing PETSc. And then use HYPRE, instead of GAMG, as the preconditioner. HYPRE is much more stable and faster for the standard Poisson matrix on a structured grid.

**Comment by shi-guangyu** [comment]
Hi, Pi-Yueh,

After using bcgs scheme, the calculation can be finished now. I checked the lift and drag coefficients as well as the vorticity fields, ans everything seemed OK. But the drag force experienced a serious oscillation at the beginning of the simulation. 

I've attached two figures showing the results from petibm-ibpm and petibm-decoupledibpm for another case (unsteady flow past a cylinder at Re=550). The ibpm gave the same result as the reference data, but the decoupled ibpm produced large force oscillations. But it seems the oscillation does not affect the periodic result in the end. Using bcgs scheme didn't improve the result.

Any comment on this?

Many thanks.

Guangyu
![dragCoefficient_ibpm](https://user-images.githubusercontent.com/25904653/76507452-bc6c7680-6444-11ea-9218-40ba437c9035.png)
![dragCoefficient_decoupledibpm](https://user-images.githubusercontent.com/25904653/76507508-d5752780-6444-11ea-8b93-86a51d1e3d52.png)

**Comment by mesnardo** [comment]
@shi-guangyu, the oscillations you see with the decoupled IBPM are expected.

The decoupled IBPM enforces the constraints of the problem (no-slip and divergence-free) sequentially (i.e., not both at the same time).
The decoupled IBPM implemented in PetIBM (application `petibm-decoupledibpm`) enforces first the no-slip condition and then, make the velocity field divergence-free (by solving a classical Poisson system).
The projection on the divergence-free space may break the no-slip condition at the boundary.

With the IBPM (application `petibm-ibpm`), the two constraints are simultaneously satisfied by the end of each time step; this done by solving a modified Poisson system for the pressure field and Lagrangian forces (grouped together under the same variable).

But as you see, the oscillations occur during the early stage of the simulation.
Once the oscillations are damped the solution with the decoupled IBPM recovers the one obtained with the IBPM.

For further details, you can read the study from Li and co-authors (2016), who proposed the decoupled IBPM (that we implemented in PetIBM).

References:

* Li, R. Y., Xie, C. M., Huang, W. X., & Xu, C. X. (2016). An efficient immersed boundary projection method for flow over complex/moving boundaries. Computers & Fluids, 140, 122-135.

**Comment by shi-guangyu** [comment]
@mesnardo If so, what are the advantages of using a decoupled method? Since you also implemented kinematics solver based on decoupled method, it should be more advantageous than the original projection method.

Thanks.

Guangyu

**Comment by mesnardo** [comment]
With the IBPM, the presence of an immersed boundary in the domain augments the size of the modified Poisson operator, with off diagonal coefficients, making the system more expensive to solve with iterative methods.
(The presence of the immersed surface has a negative impact on the condition number of the modified Poisson system.)

With the decoupled IBPM, we retrieve a classical Poisson system (same as in the Navier-Stokes solver).
The decoupling introduces an additional system to solve, for the Lagrangian forces.
However, this system is relatively small (since the number of Lagrangian markers is usually way smaller than the number of fluid points) and cheap to solve.

We decided to implement the `RigidKinematicsSolver` based on the `DecoupledIBPMSolver` to accelerate the time-to-solution.

**Comment by shi-guangyu** [comment]
Understood. Thanks a lot for your kind explaination.

Best wishes;

Guangyu
