### ISSUE TITLE
Deletion of API examples and `copy-examples`

### ISSUE THREAD

**Issue by piyueh** [barbagroup/PetIBM#162]
@mesnardo Why do the API examples have to be deleted after installation?

https://github.com/barbagroup/PetIBM/blob/ffdbe251b774aa89b103b40012a3e90057a12448/Makefile.am#L17

And is the instruction for copying examples valid?

https://github.com/barbagroup/PetIBM/blob/a6578217ec1022b380f3f2a5972c8d2868ea3202/doc/markdowns/installation.md?plain=1#L251-L260

**Comment by mesnardo** [comment]
Hey @piyueh , they are probably removed because they are not compiled with the root `make all`. To compile them, we need to change dir to the api example folder and run `make`. We have instructions in the README file of each api example.

And you are right, the `copy-examples` recipe does not work anymore. Now examples are copied into the installation directory with `make install`. (Feel free to update to docs.)

**Comment by piyueh** [comment]
resolved in #164
