### ISSUE TITLE
Investigate oscillations in u and v

### ISSUE THREAD

**Issue by anushkrish** [barbagroup/PetIBM#21]
Oscillations are observed in the contour plots of u and v when using a stretched grid and Dirichlet/Convective BCs. (In the below cases, Convective at the outlet and Dirichlet elsewhere)

Re = 40, u
![u0000300](https://cloud.githubusercontent.com/assets/6268735/3267657/8aa62312-f2d0-11e3-8a42-84866866b9b0.png)

Re = 40, v
![v0000300](https://cloud.githubusercontent.com/assets/6268735/3267663/93c42480-f2d0-11e3-800f-b18aa0c01913.png)

Re = 3000, u
![u0003000](https://cloud.githubusercontent.com/assets/6268735/3267686/d897bbee-f2d0-11e3-8663-62dbd3999cbb.png)

Re = 3000, v
![v0003000](https://cloud.githubusercontent.com/assets/6268735/3267688/e0f571f0-f2d0-11e3-895f-4aa01cef694c.png)

But the vorticity and pressure plots look clean near the edges:

Re = 3000, vorticity
![o0003000](https://cloud.githubusercontent.com/assets/6268735/3267690/e88410de-f2d0-11e3-9cce-4c8aa0ac770b.png)

Re = 3000, pressure
![p0003000](https://cloud.githubusercontent.com/assets/6268735/3267697/f626e626-f2d0-11e3-80d6-db8a9a703d46.png)

And the oscillations do not appear when using periodic BCs:

Re = 40, u (periodic in x)
![u0000300](https://cloud.githubusercontent.com/assets/6268735/3267731/6033e23a-f2d1-11e3-8cea-b8a27d248a48.png)

Re = 40, u (periodic in x and y)
![u0000300](https://cloud.githubusercontent.com/assets/6268735/3267739/832c97d2-f2d1-11e3-9a10-1f1e7a48a692.png)

They do not appear when a fully uniform grid is used (Dirichlet BC at inlet and top and bottom, convective BC at the outlet).

Re = 40, u (uniform grid in [-7.5,7.5]x[-7.5,7.5])
![u0000300](https://cloud.githubusercontent.com/assets/6268735/3267777/2c096754-f2d2-11e3-91ee-5f7bd9129a21.png)

Re = 40, v (uniform grid in [-7.5,7.5]x[-7.5,7.5])
![v0000300](https://cloud.githubusercontent.com/assets/6268735/3268013/2c384cd2-f2d6-11e3-95d6-f96daca852b3.png)

**Comment by piyueh** [comment]
I don't think this issue exists in the current version. There has been a lot of changes and bug fixes since this issue was created. I tried to run the same simulations as the ones in this issue, though there are a lot of parameter missing. And I don't see any oscillation.

## 2D Cylinder, Re150, dt=0.005, nt=24000, inlet at x-minus surface
#### u-velocity
![re150_u](https://user-images.githubusercontent.com/7220966/35459521-7a0c0d18-02ae-11e8-872e-4490b6251031.png)
#### v-velocity
![re150_v](https://user-images.githubusercontent.com/7220966/35459549-959fdb36-02ae-11e8-9384-52323d85ca88.png)

## 2D Cylinder, Re150, dt=0.005, nt=24000, inlet at y-minus surface
#### u-velocity
![re150_y_u](https://user-images.githubusercontent.com/7220966/35459558-a78c8c18-02ae-11e8-9779-f0fe63bb6c77.png)
#### v-velocity
![re150_y_v](https://user-images.githubusercontent.com/7220966/35459564-b146d1dc-02ae-11e8-82b2-51ed9ee248d4.png)

@mesnardo I think we can close this issue.

**Comment by mesnardo** [comment]
Ok to close.

**Comment by piyueh** [comment]
No oscillation detected for the 3D flat plate simulation, either.

## 3D flat plate, AoA45, Re100, inlet at x-minus surface
#### u-velocity
![movie](https://user-images.githubusercontent.com/7220966/35463259-c0846cf4-02bd-11e8-9bea-11c48f5326af.gif)
