### ISSUE TITLE
Add unit tests for the explicit terms

### ISSUE THREAD

**Issue by anushkrish** [barbagroup/PetIBM#42]
Check the convergence of
* The convection kernel
* The diffusion kernel

**Comment by mesnardo** [comment]
Done. 

Tests for the spatial convergence of the convective terms and diffusive terms have been implemented.

Convective terms exhibits second-order convergence.
Diffusive terms exhibits less than 2.0 due to the external boundaries (since we do not use ghost cells and use directly the boundary velocity value). If we check the convergence on points not close to the boundaries, we get observe second-order convergence.
