### ISSUE TITLE
setNullSpace.inl in tairaColonius

### ISSUE THREAD

**Issue by gforsyth** [barbagroup/PetIBM#55]
@anushkrish -- I'm updating everything to use Petsc 3.6 and I can't see why this file exists.  Did you have plans for it in the future?

**Comment by mesnardo** [comment]
Within PETSc-3.6.1, `KSPSetNullSpace()` is removed, and we should use `MatSetNullSpace()`, where the first argument is not the KSP but the matrix itself.

After changing the body of the methods `setNullSpace()`, we observe that:

* The unit-tests passed.

* Running the 2d cylinder (Re=40) case works.

* Running the 2d lid-driven cavity (Re=100) case does not work. It returns that the Poisson solver diverged due to reason `-8`. According to the [manual page](http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/KSP/KSP_DIVERGED_INDEFINITE_PC.html#KSP_DIVERGED_INDEFINITE_PC), it means that the preconditioner is indefinite (has both positive and negative eigenvalues), something that CG does not allow.
Fair enough, I tried to use BCGS as the Poisson solver. This time, it runs.

* The regression test, with BCGS when no immersed body, did not passed. But this is not surprising because if the relative difference between two vector fields is larger than `1.0E-06`, it does not pass. This is way too restrictive, the relative tolerance should be change to an absolute one (function `numpy.allclose()` in the Python script `regressionAnalysis.py`).

To be noted that a similar behavior happened to me and was reported in this [issue](https://github.com/barbagroup/PetIBM/issues/53).

My thought right now, is that PETSc is modifying something with the preconditioner.
To be investigated.

**Comment by anushkrish** [comment]
If you've decided to place the function that was in it elsewhere, there's no reason for the file to exist. In fact, most of the `.inl` files only exist for the sake of convenience. Otherwise, all the functions could have been defined in `NavierStokesSolver.h` or `NavierStokesSolver.cpp`.

**Comment by piyueh** [comment]
As [this page](http://www.mcs.anl.gov/petsc/documentation/changes/36.html) says:
>Removed KSPSetNullSpace() always use MatSetNullSpace() provided to the FIRST matrix argument to KSPSetOperators(), or SNESSetJacobian(), or TSSetIJacobian()` 

We may need to use `MatSetNullSpace(QTBNQ, nsp);` instead of `KSPSetNullSpace(NavierStokesSolver<dim>::ksp2, nsp);` ?

**Comment by piyueh** [comment]
Please refer to pull request #60 .
Current solution:
`KSPSetNullSpace(NavierStokesSolver<dim>::ksp2, nsp);` -> `MatSetNullSpace(this->QTBNQ, nsp);`
